/**
 * Where a dropped image's bytes live.
 *
 * Only images: a document's text is extracted once and inlined into the
 * message (see main/index.ts and core/llm/attach.ts's header for why), so
 * there is nothing left of it to store. An image cannot be inlined as text,
 * so its bytes go here and the message keeps only the reference.
 *
 * Never inline in the session JSON. `listSessions()` (core/sessions.ts) opens
 * *every* session file just to read its title, so a handful of inlined photos
 * would make the conversation rail parse megabytes on every listing -- the
 * same reason a paper's own manuscript is never written to disk either.
 *
 * One directory per conversation, `CONFIG_DIR/attachments/<sessionId>/`,
 * owner-only like everything else MyRA writes for itself.
 */

import { readFile, readdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { CONFIG_DIR, makeOwnDir, OWNER_ONLY_FILE } from "../core/paths.ts";
import { assertAttachmentId, attachmentId } from "../core/llm/attach.ts";
import { extensionFor, sniffImage } from "../core/images/generate.ts";

/** A session id is generated by this process, never typed by a user -- but it
 *  still lands in a path, so it is still checked rather than trusted. */
function assertSessionId(id: string): string {
  if (!/^[A-Za-z0-9._-]+$/.test(id) || id === "." || id === "..") {
    throw new Error(`invalid session id ${JSON.stringify(id)}`);
  }
  return id;
}

function attachmentsRoot(): string {
  return join(CONFIG_DIR, "attachments");
}

function sessionDir(sessionId: string): string {
  return join(attachmentsRoot(), assertSessionId(sessionId));
}

/** 64 MB, the same ceiling image generation already treats as absurd for a picture. */
const MAX_IMAGE_BYTES = 64 * 1024 * 1024;

export interface SavedImage {
  id: string;
  mime: string;
  bytes: number;
}

/**
 * Write a dropped image's bytes, sniffed rather than trusted by extension.
 *
 * The renderer downscales before sending -- it is the only side with a DOM --
 * so this never resizes anything; it validates and stores what arrived.
 */
export async function saveImageAttachment(sessionId: string, bytes: Uint8Array): Promise<SavedImage> {
  if (bytes.byteLength > MAX_IMAGE_BYTES) {
    throw new Error(`That image is too large (${Math.round(bytes.byteLength / 1024 / 1024)} MB).`);
  }
  const mime = sniffImage(bytes);
  if (!mime) throw new Error("That does not look like an image MyRA can read.");

  const dir = sessionDir(sessionId);
  await makeOwnDir(dir);
  const id = attachmentId();
  const path = join(dir, `${id}.${extensionFor(mime)}`);
  await writeFile(path, bytes, { mode: OWNER_ONLY_FILE });
  return { id, mime, bytes: bytes.byteLength };
}

/** Every file under a session's attachment directory, keyed by attachment id. */
async function filesByPrefix(sessionId: string): Promise<Map<string, string>> {
  const dir = sessionDir(sessionId);
  let names: string[];
  try {
    names = await readdir(dir);
  } catch {
    return new Map();
  }
  const out = new Map<string, string>();
  for (const name of names) {
    const dot = name.indexOf(".");
    const id = dot === -1 ? name : name.slice(0, dot);
    out.set(id, join(dir, name));
  }
  return out;
}

/**
 * An image's bytes, as a `data:` URI -- or nothing, when the file is not
 * there. Missing is not an error here: a reference to a deleted conversation's
 * attachment, or one removed by hand, degrades the message to plain text
 * rather than failing the whole request (see `expandImages`).
 */
export async function readImageDataUri(
  sessionId: string,
  id: string,
  mime: string,
): Promise<string | undefined> {
  try {
    const files = await filesByPrefix(sessionId);
    const path = files.get(assertAttachmentId(id));
    if (!path) return undefined;
    const bytes = await readFile(path);
    return `data:${mime};base64,${bytes.toString("base64")}`;
  } catch {
    return undefined;
  }
}

/** Remove one attachment -- the composer's own × on a chip, before it is ever sent. */
export async function deleteAttachment(sessionId: string, id: string): Promise<void> {
  const files = await filesByPrefix(sessionId);
  const path = files.get(assertAttachmentId(id));
  if (path) await rm(path, { force: true });
}

/** Every attachment a conversation ever held, removed with it. */
export async function deleteSessionAttachments(sessionId: string): Promise<void> {
  await rm(sessionDir(sessionId), { recursive: true, force: true });
}

/**
 * Every session folder under the attachments root, for `deleteAllSessions`.
 *
 * Reads the root directly rather than asking `listSessions()` for the id
 * list: a session with an attachment but no message was never saved (see
 * main/index.ts's `myra:new-session`), so it has no session file to list
 * but still has bytes on disk worth clearing.
 *
 * `keep` is the conversations a project holds, which `deleteAllSessions` spares
 * for the same reason -- an image dropped into a filed conversation has to
 * outlive the broom as surely as the message referring to it does, or that
 * message degrades to plain text the next time it is sent.
 */
export async function deleteAllAttachments(keep: ReadonlySet<string> = new Set()): Promise<void> {
  if (!keep.size) {
    await rm(attachmentsRoot(), { recursive: true, force: true });
    return;
  }
  let names: string[];
  try {
    names = await readdir(attachmentsRoot());
  } catch {
    return;
  }
  for (const name of names) {
    if (keep.has(name)) continue;
    await rm(join(attachmentsRoot(), name), { recursive: true, force: true });
  }
}
