#!/usr/bin/env bash
# Install Docker CE and bring up Karen's SearXNG container, inside the VM.
#
# Run this once, in the VM:
#     ./scripts/install-searxng.sh
#
# It will ask for your sudo password (Docker needs root to install). Everything
# it starts binds to 127.0.0.1 — not reachable from the host or the LAN.
#
# NOTE ON STYLE: this script runs under `set -o pipefail`, so it deliberately
# never writes `some_command | grep -q ...`. grep -q exits on the first match,
# the upstream command dies of SIGPIPE (141), and pipefail reports that as the
# pipeline's status -- so the test fails precisely when it should succeed.
# Output is captured into a variable and matched with `case` instead.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SEARXNG_DIR="$REPO_ROOT/vm/searxng"
PORT="${KAREN_SEARXNG_PORT:-8888}"

say()  { printf '\n\033[1;33m==> %s\033[0m\n' "$*"; }
warn() { printf '\n\033[1;31m!! %s\033[0m\n' "$*" >&2; }
fail() { printf '\n\033[1;31m!! %s\033[0m\n' "$*" >&2; exit 1; }

[ -f "$SEARXNG_DIR/docker-compose.yaml" ] || fail "cannot find $SEARXNG_DIR/docker-compose.yaml"

listening="$(ss -tlnp 2>/dev/null || true)"
case "$listening" in
  *":$PORT "*) fail "Port $PORT is already in use inside this VM.
Set KAREN_SEARXNG_PORT to a free port and re-run." ;;
esac

# ---------------------------------------------------------------- Docker ----
if ! command -v docker >/dev/null 2>&1; then
  say "Installing Docker CE from the official repository (needs sudo)"
  . /etc/os-release
  sudo install -m 0755 -d /etc/apt/keyrings
  # wget, not curl: curl is not installed on a stock image of this VM.
  sudo wget -qO /etc/apt/keyrings/docker.asc https://download.docker.com/linux/ubuntu/gpg
  sudo chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable" \
    | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null

  # A broken third-party repo (CRAN, a stale PPA) makes apt-get update exit
  # non-zero even when every list we care about fetched perfectly. That is not
  # our failure to own, so tolerate it -- then PROVE docker-ce is available.
  sudo apt-get update || warn "apt-get update reported errors; checking whether that mattered"

  policy="$(apt-cache policy docker-ce 2>/dev/null || true)"
  case "$policy" in
    *download.docker.com*) say "Docker's package list is available" ;;
    *) fail "Docker's package list is not available.
Check that this line fetched without error:
    $(cat /etc/apt/sources.list.d/docker.list 2>/dev/null)
Then re-run this script." ;;
  esac

  sudo apt-get install -y docker-ce docker-ce-cli containerd.io \
    docker-buildx-plugin docker-compose-plugin
else
  say "Docker already present: $(docker --version)"
fi

if ! docker compose version >/dev/null 2>&1 && ! sudo docker compose version >/dev/null 2>&1; then
  fail "the docker compose plugin is not available"
fi

user_groups="$(id -nG "$USER" 2>/dev/null || true)"
case " $user_groups " in
  *" docker "*) ;;
  *) say "Adding $USER to the docker group"
     sudo usermod -aG docker "$USER"
     NEEDS_RELOGIN=1 ;;
esac

# ----------------------------------------------------------------- Config ---
# Resolve a CONCRETE image version rather than riding "latest".
#
# SearXNG publishes every day or two, so "latest" means "whatever was built in
# the last few hours" -- you would silently run a different image on every pull.
# This container is the one that fetches and parses hostile HTML from a dozen
# search engines, so it is the wrong place to be unpinned. Resolve once here,
# record it, and make updating a deliberate act.
resolve_version() {
  local body
  body="$(wget -qO- --timeout=15 \
    "https://hub.docker.com/v2/repositories/searxng/searxng/tags?page_size=25&ordering=last_updated" \
    2>/dev/null || true)"
  # sed rather than `grep | head`: sed -n '1p' consumes all input, so nothing
  # upstream is killed by SIGPIPE (see the note at the top of this file).
  printf '%s' "$body" \
    | tr ',' '\n' \
    | sed -n 's/.*"name":"\([0-9]\{4\}\.[0-9]\{1,\}\.[0-9]\{1,\}-[0-9a-f]\{1,\}\)".*/\1/p' \
    | sed -n '1p'
}

if [ ! -f "$SEARXNG_DIR/.env" ]; then
  say "Resolving the current SearXNG version"
  VERSION="$(resolve_version || true)"
  if [ -z "$VERSION" ]; then
    VERSION="latest"
    warn "Could not reach Docker Hub to resolve a version; falling back to \"latest\".
   Pin it later by setting SEARXNG_VERSION in $SEARXNG_DIR/.env"
  else
    say "Pinning to $VERSION"
  fi

  say "Generating SearXNG configuration"
  ( umask 077
    cat > "$SEARXNG_DIR/.env" <<ENV
# Generated by install-searxng.sh. Local secret; do not commit.
SEARXNG_SECRET=$(openssl rand -hex 32)
# Pinned deliberately. To update: change this, then \`docker compose up -d\`.
# Current tags: https://hub.docker.com/r/searxng/searxng/tags
SEARXNG_VERSION=$VERSION
# The port SearXNG binds inside the container AND the port published on the
# host. Deliberately no SEARXNG_HOST here: this file is handed to the container
# verbatim, and there it would mean "bind this address" -- pinning it to
# loopback would make SearXNG unreachable through the port mapping. Host-side
# exposure is restricted in docker-compose.yaml instead.
SEARXNG_PORT=$PORT
SEARXNG_BASE_URL=http://127.0.0.1:$PORT/
ENV
  )
else
  say "Reusing existing $SEARXNG_DIR/.env"
fi

# ------------------------------------------------------------------ Start ---
# Group membership does not apply to the current shell, so the first run after
# installing Docker still needs sudo.
DOCKER="docker"
docker info >/dev/null 2>&1 || DOCKER="sudo docker"

say "Starting SearXNG (first run pulls the image; this can take a minute)"
( cd "$SEARXNG_DIR" && $DOCKER compose up -d )

say "Waiting for SearXNG to answer JSON"
for _ in $(seq 1 45); do
  body="$(wget -qO- "http://127.0.0.1:$PORT/search?q=test&format=json" 2>/dev/null || true)"
  case "$body" in
    *'"results"'*)
      say "SearXNG is up at http://127.0.0.1:$PORT and returning JSON."
      # Record exactly which image is running, so this install is auditable.
      pinned="$(sed -n 's/^SEARXNG_VERSION=//p' "$SEARXNG_DIR/.env" || true)"
      digest="$($DOCKER image inspect --format '{{index .RepoDigests 0}}' \
        "docker.io/searxng/searxng:${pinned:-latest}" 2>/dev/null || true)"
      if [ -n "$digest" ]; then
        printf '%s\n' "$digest" > "$SEARXNG_DIR/installed-image.txt"
        echo "Running image: $digest"
      fi
      [ -n "${NEEDS_RELOGIN:-}" ] && echo "Log out and back in to use docker without sudo."
      echo "Karen's tools default to this address, so nothing further to configure."
      exit 0 ;;
  esac
  sleep 2
done

fail "SearXNG did not answer within 90s.
Check the logs:   (cd $SEARXNG_DIR && $DOCKER compose logs --tail=50)
A 403 from the JSON endpoint means core-config/settings.yml did not load."
